<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to login' => 'Vissza a belépésre',
    'Change account' => 'Fiók váltása',
    'Check your email for further instructions.' => 'A további lépésekért ellenőrizze a bejövő e-mail-jeit.',
    'E-mail address' => 'E-mail cím',
    'If you forgot your password you can' => 'Ha elfelejtette jelszavát,',
    'Incorrect login informations.' => 'Helytelen bejelentkezési adatok.',
    'Login' => 'Belépés',
    'New password' => 'Új jelszó',
    'Password' => 'Jelszó',
    'Please choose your new password:' => 'Kérjük, válassza ki új jelszavát:',
    'Please fill out the following fields to login:' => 'A bejelentkezéshez kérjük, töltse ki az alábbi mezőket:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Kérjük, töltse ki az e -mail címét. A rendszer elküldi a linket a jelszó visszaállításához.',
    'Repeat new password' => 'Új jelszó megerősítése',
    'Request password reset' => 'Jelszó visszaállítása',
    'Reset password' => 'Jelszó visszaállítása',
    'Save' => 'Mentés',
    'Send' => 'Küldés',
    'Too many incorrect login attempts.' => 'Túl sok helytelen bejelentkezési kísérlet.',
    'You have successfully set the new password.' => 'Sikeresen beállította az új jelszót.',
    'reset it' => 'visszaállíthatja',
    '{appName} :: Password reset' => '{appName} :: Jelszó visszaállítása',
    'Forgot your password?' => 'Elfejetette a jelszavát?',
];
