<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to login' => 'Back to login',
    'Change account' => 'Change account',
    'Check your email for further instructions.' => 'Check your email for further instructions.',
    'E-mail address' => 'E-mail address',
    'If you forgot your password you can' => 'If you forgot your password you can',
    'Incorrect login informations.' => 'Incorrect login informations.',
    'Login' => 'Login',
    'New password' => 'New password',
    'Password' => 'Password',
    'Please choose your new password:' => 'Please choose your new password:',
    'Please fill out the following fields to login:' => 'Please fill out the following fields to login:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Please fill out your email. A link to reset password will be sent there.',
    'Repeat new password' => 'Repeat new password',
    'Request password reset' => 'Request password reset',
    'Reset password' => 'Reset password',
    'Save' => 'Save',
    'Send' => 'Send',
    'Too many incorrect login attempts.' => 'Too many incorrect login attempts.',
    'You have successfully set the new password.' => 'You have successfully set the new password.',
    'reset it' => 'reset it',
    '{appName} :: Password reset' => '{appName} :: Password reset',
    'Forgot your password?' => 'Forgot your password?',
];
